server:
  port: 9002

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000 # 剔除服务间隔
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
