spring:
  application:
    name: provider-bar
  profiles:
    active:
      - dev

logging:
  config: classpath:config/logback-spring.xml

feign:
  hystrix:
    enabled: true

info:
  app.name: ${spring.application.name}:${server.port}
  company.name: www.bar.com

