# 默认配置
server:
  port: 8071

spring:
  application:
    name: bar-service
  profiles:
    active:
      - bar1

---
server:
  port: 8071
spring:
  profiles: bar1
  cloud:
    sentinel:
      transport:
        port: 8721 # 与sentinel控制台传输端口
        dashboard: 127.0.0.1:8088 # 服务注册到sentinel控制台地址
eureka:
  instance:
    hostname: ${spring.application.name} # 如果配置，注册中心页面上url是主机名
    prefer-ip-address: true # 当配置eureka.instance.hostname时强制在url中使用ip地址
    lease-renewal-interval-in-seconds: 3 # 更新租约间隔
    lease-expiration-duration-in-seconds: 9 # 租约过期时间
  client:
    registry-fetch-interval-seconds: 10 # 拉取注册信息间隔
    service-url:
      defaultZone: http://localhost:9001/eureka/

---
server:
  port: 8072
spring:
  profiles: bar2
  cloud:
    sentinel:
      transport:
        port: 8722
        dashboard: 127.0.0.1:8088 # 服务注册到sentinel控制台地址
eureka:
  instance:
    hostname: ${spring.application.name} # 如果配置，注册中心页面上url是主机名
    prefer-ip-address: true # 当配置eureka.instance.hostname时强制在url中使用ip地址
    lease-renewal-interval-in-seconds: 3 # 更新租约间隔
    lease-expiration-duration-in-seconds: 9 # 租约过期时间
  client:
    registry-fetch-interval-seconds: 10 # 拉取注册信息间隔
    service-url:
      defaultZone: http://localhost:9002/eureka/