server:
  port: 8080
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: node5:8848
    sentinel:
      transport:
        port: 8721
        dashboard: node5:8010
feign:
  sentinel:
    enabled: true

logging:
  level:
    org.springframework.cloud: debug
    com.alibaba.cloud: debug
    org.springframework.boot: debub

