spring:
  application:
    name: zuul-getway

server:
  port: 5001

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
   prefix:  /api

info:
  app.name: ${spring.application.name}:${server.port}
  company.name: www.foo.com
