spring:
  application:
    name: zuul-getway

server:
  port: 5001

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/

zuul:
  prefix:  /api
#  routes:
#    client-a:
#      path: /client/**
#      serviceId: client-a

security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:7777/uaa/oauth/token #令牌端点
      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize #授权端点
      client-id: zuul-getway #OAuth2客户端ID
      client-secret: secret #OAuth2客户端密钥
    resource:
      jwt:
        key-value: springcloud123 #使用对称加密方式，默认算法为HS256

info:
  app.name: ${spring.application.name}:${server.port}
  company.name: www.foo.com
