server:
  port: 7002

spring:
  application:
    name: eureka-clouster

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/

info:
  app.name: eureka-${server.port}
  company.name: www.foo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
