server:
  port: 8086
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: node5:8848
    sentinel:
      transport:
        port: 8720
        dashboard: node5:8010

logging:
  level:
    org.springframework.cloud: debug
    com.alibaba.cloud: debug
    org.springframework.boot: debub

