spring:
  application:
    name: consul-client # 服务名称 唯一标示
  cloud:
    consul:
      host: node3
      port: 8500
    discovery:
      service-name: ${spring.application.name} # 注册服务的名称

server:
  port: 8800 # 服务端口号

consul-foo-service: #这个是微服务的id
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略


feign:
  hystrix:
    enabled: true # 开启openfeign支持hystrix
  client:
    config:
      consul-foo-service: # default 针对所有服务都生效
        connect-timeout: 5000 # 连接超时时间 单位毫秒
        read-timeout: 5000 # 读超时时间 单位毫秒
        logger-level: full

logging:
  level:
    org:
      consul:
        client:
          feign: debug # feign调用接口所在的包必须为debug级别

