spring:
  application:
    name: nacos-admin-service # 服务名称 唯一标示
  cloud:
    nacos:
      server-addr: node3:8848 # 声明注册中心地址
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr} # 注册地址的使用，默认配置
  jmx:
    enabled: true

server:
  port: 9900 # 服务端口号

management: # 建议所有服务都配置，默认引入actuator
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.admin: DEBUG
  file: D:/logs/admin-service.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
