spring:
  application:
    name: getway-consul # 服务名称 唯一标示
  cloud:
    consul:
      host: node3
      port: 8500
    discovery:
      service-name: ${spring.application.name} # 注册服务的名称
    gateway:
      routes:
        - id: foo-service  # 路由id唯一标示，建议与服务名称相同
          uri: http://localhost:9902  # 路由服务地址
          predicates:  # 路由规则
            - Path=/foo/**  # 路径规则，以/foo/开头的请求转发给http://localhost:8500，** 表示匹配多级路径
        - id: consul-client
          uri: lb://consul-client   # lb 转发使用负载均衡策略
          predicates:
            - Path=/invoke/**
      discovery:
        locator:
          enabled: true  # 开启根据服务名称动态路由
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8000 # 服务端口号

