server:
  port: 9001

spring:
  application:
    name: consumer-foo
  mvc:
    dateFormat: yyyy-MM-dd HH:mm:ss
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8

logging:
  config: classpath:config/logback-spring.xml

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

info:
  app.name: ${spring.application.name}:${server.port}
  company.name: www.foo.com
