server:
  port: 9001

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

info:
  app.name: ${spring.application.name}:${server.port}
  company.name: www.foo.com
