server:
  port: 8001

spring:
  application:
    name: provider

logging:
  level:
    root: debug


eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true

info:
  app.name: provider-${server.port}
  company.name: www.foo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


