server:
  port: 8888

spring:
  application:
    name: invoke-bar-service
  cloud:
    sentinel:
      transport:
        port: 8723
        dashboard: 127.0.0.1:8088 # 服务注册到sentinel控制台地址
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:9001/eureka/

ribbon:
  eager-load: # 饿汉加载
    enabled: true
  ReadTimeout: 2000 # 默认5s
  ConnectTimeout: 2000 # 默认2s
  MaxAutoRetries: 1 # 重试次数
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡策略

feign:
  sentinel:
    enabled: true
  compression: # reqeust、response开启压缩
    request:
      enabled: true
      mime-types: # 设置压缩的数据类型，以下是默认值
        - text/html
        - application/xml
        - application/json
      min-request-size: 1024 # 超过该值触发压缩，默认2048
    response:
      enabled: true
  client:
    config:
      foo-service: # 对应服务名称
        loggerLevel: FULL

logging:
  level:
    org.invoke.feign.FooServiceFeign: debug
