server:
  port: 8102

spring:
  application:
    name: foo-service
  mvc:
    dateFormat: yyyy-MM-dd HH:mm:ss
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  instance:
   preferIpAddress: true
   instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/ #,http://admin:admin@127.0.0.1:8762/eureka/

feign:
  hystrix:
    enabled: true
  httpclient:
   enabled: false
  okhttp:
    enabled: true # 替换feign的httpclient为okhttp