spring:
  application:
    name: provider-foo
  profiles:
    active:
      - dev

logging:
  config: classpath:config/logback-spring.xml

info:
  app.name: ${spring.application.name}:${server.port}
  company.name: www.foo.com
