server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: D:/data/repast/tomcat/

# datasource
spring:
  datasource:
    url: jdbc:mysql://47.106.214.111:3306/canteen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: zyb
    password:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialCize: 5    # 初始化大小
    minIdle: 20       # 最小
    maxActive: 200    # 最大
    maxWait: 60000  # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL   # 验证连接有效与否的SQL，不同的数据配置不同
    testWhileIdle: true   # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testOnBorrow: false   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true    # 打开PSCache，并且指定每个连接上PSCache的大小
    MaxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
    filters: stat,wall,slf4j    # 配置监控统计拦截的filters
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000    # 打开mergeSql功能；慢SQL记录