server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: D:/tomcat/
# log
logging:
  level:
    root: debug
    org:
      springframework: debug
    com:
      yuneke:
        mapper: debug
  file: D:/log/repoast_pos_helper.log

# datasource
spring:
  datasource:
    url: jdbc:mysql://47.106.214.111:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: zyb
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 20
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000