spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0


