spring:
  application:
    name: eureka-client # 服务名称 唯一标示
  profiles:
    active:
      - dev

server:
  port: 8800 # 服务端口号

eureka:
  client:
    serverice-url:
      defaultZone: http://localhost:8761/eureka # eureka server注册中心地址
  instance:
    lease-renewal-interval-in-seconds: 10 # Eureka客户端向服务心跳的时间间隔，默认是30秒
    lease-expiration-duration-in-seconds: 30 #  Eureka服务端在收到一次心跳后的超时时间，默认是90s
