spring:
  application:
    name: nacos-gateway # 服务名称 唯一标示
  cloud:
    nacos:
      server-addr: node3:8848 # 声明注册中心地址
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr} # Nacos Server 启动监听的ip地址和端口，默认配置
    gateway:
      routes:
        - id: nacos-foo-service
          uri: lb://nacos-foo-service   # lb 转发使用负载均衡策略
          predicates:
            - Path=/nacos-foo-service/**
            - My=liyan # 自定义断言
          filters:
            - StripPrefix=1 # 剔除服务名称
            - My=liyan

management:
  endpoints:
    web:
      exposure:
        include: "*" # web端点暴露
    gateway:
      enabled: true # 开启gateway端点

server:
  port: 8000 # 服务端口号

