spring:
  application:
    name: foo-service # 服务名称 唯一标示
  cloud:
    consul:
      host: node3
      port: 8500
    discovery:
      service-name: ${spring.application.name} # 注册服务的名称

server:
  port: 9900 # 服务端口号

