# 默认配置
server:
  port: 8080

spring:
  application:
    name: foo-service
  profiles:
    active:
      - foo1
---
server:
  port: 8081
spring:
  profiles: foo1
eureka:
  instance:
    hostname: ${spring.application.name} # 如果配置，注册中心页面上url是主机名
    prefer-ip-address: true # 当配置eureka.instance.hostname时强制在url中使用ip地址
    lease-renewal-interval-in-seconds: 3 # 更新租约间隔
    lease-expiration-duration-in-seconds: 9 # 租约过期时间
  client:
    registry-fetch-interval-seconds: 10 # 拉取注册信息间隔
    service-url:
      defaultZone: http://localhost:9001/eureka/

---
server:
  port: 8082
spring:
  profiles: foo2
eureka:
  instance:
    hostname: ${spring.application.name} # 如果配置，注册中心页面上url是主机名
    prefer-ip-address: true # 当配置eureka.instance.hostname时强制在url中使用ip地址
    lease-renewal-interval-in-seconds: 3 # 更新租约间隔
    lease-expiration-duration-in-seconds: 9 # 租约过期时间
  client:
    registry-fetch-interval-seconds: 10 # 拉取注册信息间隔
    service-url:
      defaultZone: http://localhost:9002/eureka/