server:
  port: 8002

spring:
  application:
    name: microservicecloud-consumer-dept-feign

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/

feign:
  hystrix:
    enabled: true